@startuml editEmployee
actor User
participant メインスレッド
participant サブスレッド
Database CSVデータ

== 詳細情報表示 ==
User -> メインスレッド : 詳細情報表示
User -> メインスレッド : 編集ボタン押下

== 編集画面表示 ==
メインスレッド -> メインスレッド : 編集画面に遷移
User -> メインスレッド : 編集情報入力
alt 編集情報を保存するとき
    User -> メインスレッド : 保存ボタン押下

    == データ処理 ==
    par メインスレッド：UIの制御
        メインスレッド -> User : 画面要素をすべて操作不可に
        メインスレッド -> User : 処理中メッセージ表示
    else サブスレッド：データ更新処理
        メインスレッド -> サブスレッド : サブスレッド作成
        メインスレッド -> サブスレッド : 編集データ送信
        メインスレッド-> サブスレッド: バリデーションチェック
        alt チェックOK
            サブスレッド -> メインスレッド : バリデーションチェックOK
            サブスレッド -> サブスレッド : ロックを取得
            サブスレッド -> CSVデータ : 該当データを更新
            CSVデータ -> サブスレッド : 処理結果を返す
            サブスレッド -> サブスレッド : ロックを解放
        else チェックNG
            サブスレッド -> メインスレッド : バリデーションチェックNG
            メインスレッド -> User : エラーメッセージ表示
        end
    end

    alt 更新成功
        サブスレッド -> メインスレッド : 更新成功
        メインスレッド-> メインスレッド:リスト更新
        メインスレッド -> サブスレッド : サブスレッド削除
        メインスレッド -> User : 画面更新
        メインスレッド -> User : 更新完了メッセージ表示
    else 更新失敗
        サブスレッド -> メインスレッド : 更新失敗
        メインスレッド -> User : エラーメッセージ表示
    end

else キャンセルボタン押下
    User -> メインスレッド : キャンセルボタン押下
    メインスレッド -> User : 確認モーダル表示
    alt キャンセル続行
        User -> メインスレッド : モーダルのOKボタンを押下
        メインスレッド -> メインスレッド  : 内容を破棄して詳細画面に遷移
    else キャンセルを止める
        User -> メインスレッド : モーダルのキャンセルボタンを押下
        メインスレッド -> User : モーダルを閉じる（そのまま詳細編集画面）
    end
end
@enduml
