@startuml eleteEmployee

actor User
participant メインスレッド
participant サブスレッド
database データCSV

'一覧画面一括削除
== 従業員の選択 ==
メインスレッド -> メインスレッド :削除ボタンの非活性化
loop
    User -> メインスレッド :選択
    メインスレッド -> メインスレッド :選択された従業員を保持する・対象の社員ID
    メインスレッド -> メインスレッド :一覧画面のチェックボックスにチェック
end
メインスレッド -> メインスレッド :削除ボタン活性化

== 従業員の削除 ==
User -> メインスレッド :削除ボタン押下
メインスレッド -> User:削除確認モーダルの表示

alt #ddf4ff はい
    User -> メインスレッド :はいを押下
    par #89d8ff
    メインスレッド -> User :画面のグレーアウト
    メインスレッド -> User :削除中モーダルの表示
    メインスレッド -> サブスレッド :サブスレッドの生成・対象の社員ID
    サブスレッド -> サブスレッド :ロックを取得
    サブスレッド -> データCSV :従業員を削除
    データCSV --> サブスレッド :
    サブスレッド -> サブスレッド :ロックを解除
    end

alt #89d8ff 更新成功
    サブスレッド -> メインスレッド :削除成功
    メインスレッド -> メインスレッド :リストを更新
    メインスレッド -> サブスレッド :サブスレッド削除
    メインスレッド -> User :一覧画面更新
    メインスレッド -> User :削除完了モーダル表示
else 更新失敗
    サブスレッド -> メインスレッド :削除失敗
    メインスレッド -> User :エラーメッセージ表示

end
else キャンセル
    User -> メインスレッド :キャンセルを押下
    メインスレッド -> User :確認モーダルを消す
end


