@startuml ClassDiagram

actor User
participant メインスレッド
participant サブスレッド
database CSV出力ファイル

'ユーザーが従業員をチェックするときの動作
==従業員の選択==
メインスレッド -> メインスレッド :CSVボタンの非活性化
loop
    User -> メインスレッド :選択
    メインスレッド -> メインスレッド :選択された従業員を保持する・対象の社員ID
    メインスレッド -> メインスレッド :一覧画面のチェックボックスにチェック
end

メインスレッド -> メインスレッド :CSVボタン活性化

'選択後、CSV出力を押下したときの動作
==CSVファイルの出力==
User -> メインスレッド :CSV出力ボタンを押下
メインスレッド -> メインスレッド :CSV出力確認モーダルを表示
    メインスレッド -> メインスレッド :画面のグレーアウト
'確認モーダルの分岐
alt はい
    User -> メインスレッド :はいを押下
    メインスレッド -> メインスレッド :CSV出力中モーダルの表示
    メインスレッド -> サブスレッド :サブスレッドの生成(保持してる従業員IDを渡す)
else キャンセル
    User -> メインスレッド :キャンセルを押下
    メインスレッド -> メインスレッド :確認モーダルを消す
    メインスレッド -> メインスレッド :グレーアウトを解除
end
'CSVファイルに書き込む動作
サブスレッド -> サブスレッド :ダウンロードフォルダがあるか確認
alt ある
    サブスレッド -> CSV出力ファイル :CSVファイルを生成
    CSV出力ファイル --> サブスレッド

    サブスレッド -> サブスレッド :CVSファイルを開く
'CSVファイルに書き込む1名ずつ書き込むループ
loop
    サブスレッド -> CSV出力ファイル :従業員を1人ずつ書き込む
    CSV出力ファイル --> サブスレッド
end
サブスレッド -> サブスレッド :close(保存)
'CSV出力完了後
サブスレッド --> メインスレッド :CSV出力完了
サブスレッド -> メインスレッド :サブスレッド終了
メインスレッド -> メインスレッド :CSV出力完了モーダル表示

else ない
    サブスレッド -> メインスレッド :エラーを返す
    サブスレッド -> サブスレッド:ロック解除
    サブスレッド -> メインスレッド :サブスレッド終了
    メインスレッド -> メインスレッド :エラー内容を表示
end

User -> メインスレッド :OKを押下
メインスレッド -> メインスレッド :モーダルを消す
メインスレッド -> メインスレッド :グレーアウトを解除

@enduml

・OK押下からは成功も失敗も一緒だからaltnの外に入れる
・グレーアウトの処理部分の変更
・再レビュー


