@startuml startup_completed

actor User
participant メインスレッド
participant サブスレッド
database データCSV


==起動==

User -> メインスレッド : アプリ起動
メインスレッド -> メインスレッド : ログフォルダ存在確認\nフォルダがなければ作成
メインスレッド -> メインスレッド : ログファイル存在確認\nファイルがなければ作成
note over メインスレッド, サブスレッド : ログファイルは日別に作成\nアプリ開いた当日のログがあるか確認
メインスレッド -> メインスレッド : データListを保持するクラスの\nインスタンスを生成
メインスレッド -> サブスレッド : サブスレッド生成

サブスレッド -> データCSV : ロックを取得
サブスレッド -> データCSV : データCSVフォルダ存在確認\nフォルダがなければ作成
サブスレッド -> データCSV : データCSV存在確認\nCSVがなければ作成
loop データCSVを最終行まで読み込む
    サブスレッド -> データCSV : データCSVを1行読み込む
    データCSV -> サブスレッド : Listに格納
    note right of サブスレッド : 次のレコードがあればループ続行
end
alt データをすべて読み込めた場合
    サブスレッド -> データCSV : ロックを解放
    サブスレッド -> メインスレッド : すべて読み込み成功
    サブスレッド -> メインスレッド : サブスレッド終了
    メインスレッド -> User : 一覧表示画面のUIを表示
else エラーになった場合
    サブスレッド -> データCSV : ロックを解放
    サブスレッド -> メインスレッド : エラーを返す
    サブスレッド -> メインスレッド : サブスレッド終了
    メインスレッド -> User : エラーメッセージを表示
end


==終了　一覧表示画面==

User -> メインスレッド : 「×」ボタン押下
メインスレッド -> User : 画面要素をすべて操作不可に
メインスレッド -> User : アプリ終了確認メッセージ表示
alt #ffcccc アプリ終了を中止する場合
    User -> メインスレッド : 「キャンセル」ボタン押下または\nアプリ終了確認を×ボタンで閉じる
    メインスレッド -> User : アプリ終了確認メッセージを非表示
    note right of User :アプリ終了せず、画面もそのまま
else アプリ終了が選択された場合
    User -> メインスレッド : 「はい」ボタン押下
    メインスレッド -> サブスレッド : 実行中の処理がないか確認
    alt #ccffcc 実行中の処理がない場合
        サブスレッド -> メインスレッド : 実行中の処理なし
        メインスレッド -> User : UIをすべて非表示にする
        メインスレッド -> User : アプリ終了
    else 何らかの処理が実行中だった場合
        サブスレッド -> サブスレッド : 実行中の処理が終わるまで待機
        alt #ccccff エラーが発生した場合
            サブスレッド -> メインスレッド : エラー発生
            メインスレッド -> User : エラーメッセージを表示
        else 問題なく処理が終わった場合
            サブスレッド -> メインスレッド : 実行中の処理終了
            メインスレッド -> User : UIをすべて非表示にする
            メインスレッド ->User : アプリ終了
        end
    end
end


==終了　詳細情報表示画面==

note over メインスレッド, サブスレッド : 一覧表示画面と同じ流れのため割愛


==終了　CSV読み込み画面==

note over メインスレッド, サブスレッド : 一覧表示画面と同じ流れのため割愛


==終了　新規追加画面==

User -> メインスレッド : 「×」ボタン押下
メインスレッド -> User : 画面要素をすべて操作不可に
メインスレッド -> User : アプリ終了確認メッセージ表示
alt #ffcccc アプリ終了を中止する場合
    User -> メインスレッド : 「キャンセル」ボタン押下または\nアプリ終了確認を×ボタンで閉じる
    メインスレッド -> User : アプリ終了確認メッセージを非表示
    note right of User :アプリ終了せず、画面もそのまま
else アプリ終了が選択された場合
    User -> メインスレッド : 「はい」ボタン押下
    メインスレッド -> サブスレッド : 実行中の処理がないか確認
    alt #ccffcc 実行中の処理がない場合
        サブスレッド -> メインスレッド : 実行中の処理なし
        メインスレッド -> User : UIをすべて非表示にする
        メインスレッド -> メインスレッド : 入力中の内容があれば破棄
        メインスレッド -> User : アプリ終了
    else 何らかの処理が実行中だった場合
        サブスレッド -> サブスレッド : 実行中の処理が終わるまで待機
        alt #ccccff エラーが発生した場合
            サブスレッド -> メインスレッド : エラー発生
            メインスレッド -> User : エラーメッセージを表示
        else 問題なく処理が終わった場合
            サブスレッド -> メインスレッド : 実行中の処理終了
            メインスレッド -> User : UIをすべて非表示にする
        メインスレッド -> メインスレッド : 入力中の内容があれば破棄
            メインスレッド ->User : アプリ終了
        end
    end
end


==終了　詳細情報編集画面==

note over メインスレッド, サブスレッド : 新規追加画面と同じ流れのため割愛
@enduml