@startuml StateDiagram_Main

title 状態遷移図【一覧表示画面】
hide empty description
scale 1100 width

' 【状態】

state 一覧表示 #SkyBlue
state アプリ終了確認
state アプリ終了中
state ソート中
state 検索 #YellowGreen
state 複数選択 #YellowGreen
state 新規追加 #YellowGreen
state 詳細情報表示 #Pink
state ログ出力
ログ出力 : 処理に失敗したときなどに記録


' 【遷移】

[*] --> 一覧表示

' アプリ終了
一覧表示 --> アプリ終了確認 : アプリの\n☒ボタン押下
アプリ終了確認 --> アプリ終了中 : はいボタン押下
アプリ終了確認 --> 一覧表示 : キャンセル /\n☒ボタン押下
アプリ終了中 --> [*] : 処理完了
アプリ終了中 : すべての処理を\n完了させてから終了処理

' ソート
一覧表示 --> ソート中 : ソートボタン押下
ソート中 --> 一覧表示 : 処理完了
ソート中 : 昇順 / 解除ボタン：△ / ▲\n降順 / 解除ボタン：▽ / ▼

' 検索（キーワード検索・絞り込み検索）
一覧表示 --> 検索 : 検索 / 絞り込み検索\nボタン押下
検索 : キーワード検索\n絞り込み検索

' 複数選択（削除・CSV出力）
一覧表示 --> 複数選択 : チェックボックス /\n全件選択ボタン押下
複数選択 : 削除 / CSV出力

' 新規追加（1名追加・CSV読込）
一覧表示 --> 新規追加 : 新規追加ボタン押下
新規追加 : 1名追加 / CSV読込

' 詳細情報表示（詳細情報編集・削除）
一覧表示 --> 詳細情報表示 : 社員ID押下
詳細情報表示 : 詳細情報編集 / 削除

@enduml