@startuml StateDiagram_EditDetails

title 状態遷移図【詳細情報編集画面】
hide empty description
scale 700 width

' 【状態】

state 詳細情報表示 #Pink

state 詳細情報編集 #YellowGreen {
    state 編集中
    state 保存中
    state 保存分岐 <<choice>>
    state 保存完了表示
    state 戻る分岐 <<choice>>
    state 入力破棄確認
    state 入力破棄中
    state 入力破棄完了表示
    state エラー表示
}


' 【遷移】

詳細情報表示 --> 編集中 : 編集ボタン押下

' 保存
編集中 --> 保存中 : 保存ボタン押下
保存中 --> 保存分岐
保存分岐 --> エラー表示 : エラー検知
エラー表示 --> 編集中 : OK /\n☒ボタン押下
' エラー表示 : 入力形式が不一致の場合など
保存分岐 --> 保存完了表示 : 処理完了
保存完了表示 -[#Blue]-> 詳細情報表示 : <color:Blue>☒ボタン押下</color>

' 戻る
編集中 --> 戻る分岐 : 戻るボタン押下
戻る分岐 --> 詳細情報表示 : [変更値なし]
戻る分岐 --> 入力破棄確認 : [変更値あり]
入力破棄確認 --> 編集中 : キャンセル /\n☒ボタン押下
入力破棄確認 --> 入力破棄中 : はいボタン押下
入力破棄中 --> 入力破棄完了表示 : 処理完了
入力破棄完了表示 --> 詳細情報表示 : ☒ボタン押下

@enduml