@startuml StateDiagram_Loading

title 状態遷移図【新規追加→CSV読込】
hide empty description
scale 1100 width

' 【状態】

state 一覧表示 #SkyBlue

state CSV読込 #YellowGreen {
    state "CSV読込\nダイアログ表示" as CSV読込ダイアログ表示
    state "CSV読込テンプレート\nダウンロード" as CSV読込テンプレートダウンロード
    state "エクスプローラー /\nファインダー表示" as フォルダ表示
    state ファイル読込中
    state データ保存確認
    state データ保存中
    state 保存完了表示
}


' 【遷移】

' テンプレダウンロード
CSV読込ダイアログ表示 --> CSV読込テンプレートダウンロード : テンプレートを\nダウンロードボタン押下
CSV読込テンプレートダウンロード --> CSV読込ダイアログ表示 : ダウンロード完了

' CSV読込
一覧表示 --> CSV読込ダイアログ表示 : 新規追加ボタン\nプルダウン"CSV読込"押下
CSV読込ダイアログ表示 --> 一覧表示 : ☒ボタン押下
CSV読込ダイアログ表示 : ①→②→③の順に遷移
CSV読込ダイアログ表示 --> フォルダ表示 : ①ファイル選択\nボタン押下
フォルダ表示 --> CSV読込ダイアログ表示 : ②アップロードしたい\nファイルを選択
CSV読込ダイアログ表示 --> ファイル読込中 : ③アップロード\nボタン押下
ファイル読込中 --> CSV読込ダイアログ表示 : エラー検知
ファイル読込中 --> データ保存確認 : ファイル読込成功
データ保存確認 --> データ保存中 : 確定ボタン押下
データ保存中 --> CSV読込ダイアログ表示 : 処理失敗
データ保存中 --> 保存完了表示 : 処理完了
保存完了表示 --> 一覧表示 : ☒ボタン押下

@enduml