@startuml StateDiagram_DetailsView

title 状態遷移図【詳細情報表示画面】
hide empty description
scale 800 width

' 【状態】

state 一覧表示 #SkyBlue
state アプリ終了確認
state アプリ終了中

state 詳細情報表示 #Pink {
    state 表示中
    state 削除確認
    state 削除中
    state 削除完了表示
}

state 詳細情報編集 #YellowGreen


' 【遷移】

一覧表示 --> 表示中 : 社員ID押下
表示中 --> 詳細情報編集 : 編集ボタン押下

' 戻る
表示中 --> 一覧表示 : 一覧に戻るボタン押下

' 削除
表示中 --> 削除確認 : 削除ボタン押下
削除確認 --> 表示中 : キャンセル /\n☒ボタン押下
削除確認 --> 削除中 : はいボタン押下
削除中 --> 削除完了表示 : 処理完了
削除完了表示 --> 一覧表示 : ☒ボタン押下

' アプリ終了
表示中 --> アプリ終了確認 : アプリの☒ボタン押下
アプリ終了確認 --> 表示中 : キャンセル /\n☒ボタン押下
アプリ終了確認 --> アプリ終了中 : はいボタン押下
アプリ終了中 --> [*] : 処理完了
アプリ終了中 : すべての処理を\n完了させてから終了処理

@enduml