@startuml StateDiagram_Search

title 状態遷移図【検索画面】
hide empty description
scale 800 width

' 【状態】

state 一覧表示 #SkyBlue

state 検索 #YellowGreen {
    state 絞り込み検索ダイアログ表示
    state 絞り込み検索中
    state キーワード検索中
}


' 【遷移】

' キーワード検索
一覧表示 --> キーワード検索中 : 検索ボタン押下
キーワード検索中 --> 一覧表示 : 処理完了
キーワード検索中 : キーワード検索可能項目：\n社員ID、氏名(フリガナ)、扱える言語

' 絞り込み検索
一覧表示 --> 絞り込み検索ダイアログ表示 : 絞り込み検索ボタン押下
絞り込み検索ダイアログ表示 --> 絞り込み検索中 : 検索するボタン押下
絞り込み検索ダイアログ表示 : 絞り込み検索可能項目：経歴、
絞り込み検索ダイアログ表示 : 研修の受講歴、備考以外のすべての項目
絞り込み検索中 --> 一覧表示 : 処理完了

@enduml