@startuml StateDiagram_Add

title 状態遷移図【新規追加→1名追加画面】
hide empty description
scale 800 width

' 【状態】

state 一覧表示 #SkyBlue
state 詳細情報表示 #Pink

state 1名追加 #YellowGreen {
    state 編集中
    state 保存中
    state 保存分岐 <<choice>>
    state 保存完了表示
    state エラー表示
    state 戻る分岐 <<choice>>
    state 入力破棄確認
    state 入力破棄中
    state 入力破棄完了表示
}


' 【遷移】

一覧表示 --> 編集中 : 新規追加ボタン\nプルダウン"1名追加"押下

' 保存
編集中 --> 保存中 : 保存ボタン押下
保存中 --> 保存分岐
保存分岐 --> エラー表示 : エラー検知
エラー表示 --> 編集中 : OK /\n☒ボタン押下
' エラー表示 : 社員IDが未入力、入力形式が不一致、\n入力した社員IDが既存データと重複する場合など
保存分岐 --> 保存完了表示 : 処理完了
保存完了表示 --> 詳細情報表示 : ☒ボタン押下

' 戻る
編集中 --> 戻る分岐 : 戻るボタン押下
戻る分岐 -[#Blue]-> 一覧表示 :<color:Blue> [入力値なし]</color>
戻る分岐 -[#Blue]-> 入力破棄確認 : <color:Blue>[入力値あり]</color>
入力破棄確認 --> 編集中 : キャンセル /\n☒ボタン押下
入力破棄確認 --> 入力破棄中 : はいボタン押下
入力破棄中 --> 入力破棄完了表示 : 処理完了
入力破棄完了表示 --> 一覧表示 : ☒ボタン押下

@enduml