@startuml StateDiagram_EditDetails

title 状態遷移図【詳細情報編集画面→アプリ終了】
hide empty description
scale 300 width

' 【状態】

state 詳細情報編集 #YellowGreen
state アプリ終了確認
state アプリ終了分岐 <<choice>>
state アプリ終了中
state 入力破棄中


' 【遷移】

' アプリ終了
詳細情報編集 --> アプリ終了確認 : アプリの\n☒ボタン押下
アプリ終了確認 --> 詳細情報編集 : キャンセル /\n☒ボタン押下
アプリ終了確認 --> アプリ終了分岐 : はいボタン押下

' [入力値なし]
アプリ終了分岐 --> アプリ終了中 : [入力値なし]
アプリ終了中 --> [*] : 処理完了
アプリ終了中 : すべての処理を\n完了させてから終了処理

' アプリ終了[入力値あり]
アプリ終了分岐 --> 入力破棄中 : [入力値あり]
入力破棄中 --> アプリ終了中 : 処理完了

@enduml